# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PBS-Logs
version:      0.04
version_from: lib/PBS/Logs.pm
installdirs:  site
requires:
    Carp:                          0
    Time::Local:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
